In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
pd.set_option("display.max_columns",None)

In [2]:
data=pd.read_csv(r"C:\Python Imarticus\Basics\Assignments\Support Vector Machine\Bank Credit Card Default Prediction\BankCreditCard.csv",header=0,index_col=0)

In [3]:
data.head()

Credit_Amount  Gender  Academic_Qualification  Marital  \
Customer ID                                                           
1                  20000.0       2                       2        1   
2                 220000.0       2                       2        2   
3                  90000.0       2                       2        2   
4                  50000.0       2                       2        1   
5                  50000.0       1                       2        1   

             Age_Years  Repayment_Status_Jan  Repayment_Status_Feb  \
Customer ID                                                          
1                   24                     2                     2   
2                   26                     0                     2   
3                   34                     0                     0   
4                   37                     0                     0   
5                   57                     0                     0   

             Repayment_Status_March  Repayment_Status_April  \
Customer ID                                                   
1                                 0                       0   
2                                 0                       0   
3                                 0                       0   
4                                 0                       0   
5                                 0                       0   

             Repayment_Status_May  Repayment_Status_June  Jan_Bill_Amount  \
Customer ID                                                                 
1                               0                      0           3933.0   
2                               0                      2           3683.0   
3                               0                      0          39339.0   
4                               0                      0          46990.0   
5                               0                      0           8637.0   

             Feb_Bill_Amount  March_Bill_Amount  April_Bill_Amount  \
Customer ID                                                          
1                     3103.0              689.0                0.0   
2                     1735.0             2682.0             3272.0   
3                    14037.0            23559.0            24332.0   
4                    48333.0            49292.0            29324.0   
5                     5570.0            35835.0            20940.0   

             May_Bill_Amount  June_Bill_Amount  Previous_Payment_Jan  \
Customer ID                                                            
1                        0.0               0.0                   0.0   
2                     3455.0            3261.0                   0.0   
3                    14848.0           15548.0                1619.0   
4                    28858.0           28547.0                3000.0   
5                    18146.0           18131.0                3000.0   

             Previous_Payment_Feb  Previous_Payment_March  \
Customer ID                                                 
1                           679.0                     0.0   
2                          2000.0                  1000.0   
3                          2500.0                  1000.0   
4                          2029.0                  1200.0   
5                         36672.0                 10000.0   

             Previous_Payment_April  Previous_Payment_May  \
Customer ID                                                 
1                               0.0                   0.0   
2                            1000.0                   0.0   
3                            1000.0                1000.0   
4                            1100.0                1069.0   
5                            9000.0                 689.0   

             Previous_Payment_June  Default_Payment  
Customer ID                                          
1                              0.0                1  
2                           

In [4]:
#Missing Values
data.isnull().sum()

Credit_Amount             0
Gender                    0
Academic_Qualification    0
Marital                   0
Age_Years                 0
Repayment_Status_Jan      0
Repayment_Status_Feb      0
Repayment_Status_March    0
Repayment_Status_April    0
Repayment_Status_May      0
Repayment_Status_June     0
Jan_Bill_Amount           0
Feb_Bill_Amount           0
March_Bill_Amount         0
April_Bill_Amount         0
May_Bill_Amount           0
June_Bill_Amount          0
Previous_Payment_Jan      0
Previous_Payment_Feb      0
Previous_Payment_March    0
Previous_Payment_April    0
Previous_Payment_May      0
Previous_Payment_June     0
Default_Payment           0
dtype: int64

In [5]:
#Label Encoding
data.dtypes

Credit_Amount             float64
Gender                      int64
Academic_Qualification      int64
Marital                     int64
Age_Years                   int64
Repayment_Status_Jan        int64
Repayment_Status_Feb        int64
Repayment_Status_March      int64
Repayment_Status_April      int64
Repayment_Status_May        int64
Repayment_Status_June       int64
Jan_Bill_Amount           float64
Feb_Bill_Amount           float64
March_Bill_Amount         float64
April_Bill_Amount         float64
May_Bill_Amount           float64
June_Bill_Amount          float64
Previous_Payment_Jan      float64
Previous_Payment_Feb      float64
Previous_Payment_March    float64
Previous_Payment_April    float64
Previous_Payment_May      float64
Previous_Payment_June     float64
Default_Payment             int64
dtype: object

In [6]:
#Splitting data into dep and ind vars
X=data.values[:,:-1]
Y=data.values[:,-1]
Y=Y.astype(int)

In [7]:
#Scaling Data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)

In [8]:
#Splitting Data into Train and Test
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3,random_state=10)

In [9]:
#Basic Model Building
from sklearn.svm import SVC
svc_model=SVC(kernel="rbf",gamma=0.1,C=1.0) 
svc_model.fit(X_train,Y_train)
Y_pred=svc_model.predict(X_test)
print(Y_pred)

[0 0 0 ... 0 0 0]


In [10]:
svc_model.score(X_train,Y_train)

0.8385714285714285

In [11]:
#Metrics Evaluation
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print()

print("classification report:")
print(classification_report(Y_test,Y_pred))

print()

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[6672  310]
 [1338  680]]

classification report:
              precision    recall  f1-score   support

           0       0.83      0.96      0.89      6982
           1       0.69      0.34      0.45      2018

    accuracy                           0.82      9000
   macro avg       0.76      0.65      0.67      9000
weighted avg       0.80      0.82      0.79      9000


Accuracy of the model:  0.8168888888888889


In [15]:
#Tuning SVM
from sklearn.svm import SVC
svc_model=SVC(kernel="rbf",gamma=0.01,C=10.0) 
svc_model.fit(X_train,Y_train)
Y_pred=svc_model.predict(X_test)

In [16]:
#Metrics Evaluation
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print()

print("classification report:")
print(classification_report(Y_test,Y_pred))

print()

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[6661  321]
 [1314  704]]

classification report:
              precision    recall  f1-score   support

           0       0.84      0.95      0.89      6982
           1       0.69      0.35      0.46      2018

    accuracy                           0.82      9000
   macro avg       0.76      0.65      0.68      9000
weighted avg       0.80      0.82      0.79      9000


Accuracy of the model:  0.8183333333333334


#### Cross validation

In [14]:
#changing SVC parameter values

from sklearn import svm
classifier=svm.SVC(kernel='rbf',C=10.0,gamma=0.001)

#performing kfold_cross_validation
from sklearn.model_selection import KFold
kfold_cv=KFold(n_splits=10)
print(kfold_cv)

from sklearn.model_selection import cross_val_score
kfold_cv_result=cross_val_score(estimator=classifier,X=X_train,y=Y_train, cv=kfold_cv)
print(kfold_cv_result)

print(kfold_cv_result.mean())

KFold(n_splits=10, random_state=None, shuffle=False)
[0.80857143 0.82047619 0.83142857 0.81761905 0.81619048 0.82904762
 0.82761905 0.82095238 0.8147619  0.8152381 ]
0.8201904761904762


In [12]:
#Using LogisticRegression

from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()

#performing kfold_cross_validation
from sklearn.model_selection import KFold
kfold_cv=KFold(n_splits=10)
print(kfold_cv)

from sklearn.model_selection import cross_val_score
kfold_cv_result=cross_val_score(estimator=classifier,X=X_train,y=Y_train, cv=kfold_cv)
print(kfold_cv_result)

print(kfold_cv_result.mean())

KFold(n_splits=10, random_state=None, shuffle=False)
[0.81190476 0.81238095 0.82904762 0.81428571 0.81142857 0.82761905
 0.82238095 0.82       0.81238095 0.81333333]
0.8174761904761905


In [13]:
#Using KNN

from sklearn.neighbors import KNeighborsClassifier

classifier=KNeighborsClassifier(n_neighbors=11, metric='euclidean')

#performing kfold_cross_validation
from sklearn.model_selection import KFold
kfold_cv=KFold(n_splits=10)
print(kfold_cv)

from sklearn.model_selection import cross_val_score
kfold_cv_result=cross_val_score(estimator=classifier,X=X_train,y=Y_train, cv=kfold_cv)
print(kfold_cv_result)

print(kfold_cv_result.mean())

KFold(n_splits=10, random_state=None, shuffle=False)
[0.81666667 0.80238095 0.81428571 0.80238095 0.81380952 0.81333333
 0.81809524 0.80809524 0.80285714 0.80761905]
0.809952380952381


In [ ]:
'''After Cross validation we can see that compared to Logistic and KNN, SVM (with tuned hyper parameters) will give better accuracy'''