In [116]:
import pandas as pd
import numpy as np

In [117]:
cars_data=pd.read_csv(r"C:\Python Imarticus\Basics\Decision Tree\cars.csv",header=None)
cars_data.head()

0      1  2  3      4     5      6
0  vhigh  vhigh  2  2  small   low  unacc
1  vhigh  vhigh  2  2  small   med  unacc
2  vhigh  vhigh  2  2  small  high  unacc
3  vhigh  vhigh  2  2    med   low  unacc
4  vhigh  vhigh  2  2    med   med  unacc

In [118]:
print(cars_data.shape)
print()
print(cars_data.info())

(1728, 7)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       1728 non-null   object
 1   1       1728 non-null   object
 2   2       1728 non-null   object
 3   3       1728 non-null   object
 4   4       1728 non-null   object
 5   5       1728 non-null   object
 6   6       1728 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB
None


In [119]:
cars_data.columns = ['buying', 'maint', 'doors', 'persons', 'lug_boot','safety', 'classes']
cars_data.head()

buying  maint doors persons lug_boot safety classes
0  vhigh  vhigh     2       2    small    low   unacc
1  vhigh  vhigh     2       2    small    med   unacc
2  vhigh  vhigh     2       2    small   high   unacc
3  vhigh  vhigh     2       2      med    low   unacc
4  vhigh  vhigh     2       2      med    med   unacc

### Pre Processing Data

In [120]:
#Missing Values

cars_data.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
classes     0
dtype: int64

In [121]:
#optional to create copy of Df(general practice in industry)

cars_df=pd.DataFrame.copy(cars_data)

In [122]:
colname=[]
for x in cars_df.columns:
    if cars_df[x].dtype=='object':
        colname.append(x)

from sklearn import preprocessing
le=preprocessing.LabelEncoder()
for x in colname:
    cars_df[x]=le.fit_transform(cars_df[x])
    le_name_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
    print('Feature', x)
    print('mapping', le_name_mapping)

Feature buying
mapping {'high': 0, 'low': 1, 'med': 2, 'vhigh': 3}
Feature maint
mapping {'high': 0, 'low': 1, 'med': 2, 'vhigh': 3}
Feature doors
mapping {'2': 0, '3': 1, '4': 2, '5more': 3}
Feature persons
mapping {'2': 0, '4': 1, 'more': 2}
Feature lug_boot
mapping {'big': 0, 'med': 1, 'small': 2}
Feature safety
mapping {'high': 0, 'low': 1, 'med': 2}
Feature classes
mapping {'acc': 0, 'good': 1, 'unacc': 2, 'vgood': 3}


In [123]:
cars_df.head()

buying  maint  doors  persons  lug_boot  safety  classes
0       3      3      0        0         2       1        2
1       3      3      0        0         2       2        2
2       3      3      0        0         2       0        2
3       3      3      0        0         1       1        2
4       3      3      0        0         1       2        2

In [124]:
cars_df.classes.value_counts()

2    1210
0     384
1      69
3      65
Name: classes, dtype: int64

In [125]:
#Splitting data into ind and dep var

X=cars_df.values[:,:-1]
Y=cars_df.values[:,-1]
Y=Y.astype(int)

In [126]:
#Scaling data: Optional here as we have almost we have same range values

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)

In [127]:
#Splitting data

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3,random_state=10)

### Bagging

#### Model1: Extra Trees Classifier

In [34]:
from sklearn.ensemble import ExtraTreesClassifier
model=ExtraTreesClassifier(n_estimators=10,random_state=10)
model.fit(X_train,Y_train)
Y_pred=model.predict(X_test)

In [35]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print()

print("classification report:")
print(classification_report(Y_test,Y_pred))

print()

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[ 95   2   5   0]
 [  2  19   0   0]
 [ 17   0 354   0]
 [  2   1   0  22]]

classification report:
              precision    recall  f1-score   support

           0       0.82      0.93      0.87       102
           1       0.86      0.90      0.88        21
           2       0.99      0.95      0.97       371
           3       1.00      0.88      0.94        25

    accuracy                           0.94       519
   macro avg       0.92      0.92      0.92       519
weighted avg       0.95      0.94      0.95       519


Accuracy of the model:  0.9441233140655106


In [ ]:
'''N_estimators=10 is default, where we got above accuracy. To increase it we can change the n value and see for better 
accuracy. Also the hyper parameters we used for pruining for DT can also be used here for pruning.'''

In [36]:
#Change n value 

from sklearn.ensemble import ExtraTreesClassifier
model=ExtraTreesClassifier(n_estimators=100,random_state=10)
model.fit(X_train,Y_train)
Y_pred=model.predict(X_test)

In [37]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print()

print("classification report:")
print(classification_report(Y_test,Y_pred))

print()

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[101   1   0   0]
 [  3  18   0   0]
 [  1   0 370   0]
 [  1   2   0  22]]

classification report:
              precision    recall  f1-score   support

           0       0.95      0.99      0.97       102
           1       0.86      0.86      0.86        21
           2       1.00      1.00      1.00       371
           3       1.00      0.88      0.94        25

    accuracy                           0.98       519
   macro avg       0.95      0.93      0.94       519
weighted avg       0.98      0.98      0.98       519


Accuracy of the model:  0.9845857418111753


#### Model2: Random Forest Classifier

In [38]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=10,random_state=10)
model.fit(X_train,Y_train)
Y_pred=model.predict(X_test)

In [39]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print()

print("classification report:")
print(classification_report(Y_test,Y_pred))

print()

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[ 98   3   1   0]
 [  3  17   0   1]
 [  2   0 369   0]
 [  5   2   0  18]]

classification report:
              precision    recall  f1-score   support

           0       0.91      0.96      0.93       102
           1       0.77      0.81      0.79        21
           2       1.00      0.99      1.00       371
           3       0.95      0.72      0.82        25

    accuracy                           0.97       519
   macro avg       0.91      0.87      0.88       519
weighted avg       0.97      0.97      0.97       519


Accuracy of the model:  0.9672447013487476


In [ ]:
'''N_estimators=10 is default, where we got above accuracy. To increase it we can change the n value and see for better 
accuracy. Also the hyper parameters we used for pruining for DT can also be used here for pruning.'''

In [80]:
#change n value 

from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=1000,random_state=10)
model.fit(X_train,Y_train)
Y_pred=model.predict(X_test)

In [81]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print()

print("classification report:")
print(classification_report(Y_test,Y_pred))

print()

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[ 99   3   0   0]
 [  1  19   0   1]
 [  2   0 369   0]
 [  1   0   0  24]]

classification report:
              precision    recall  f1-score   support

           0       0.96      0.97      0.97       102
           1       0.86      0.90      0.88        21
           2       1.00      0.99      1.00       371
           3       0.96      0.96      0.96        25

    accuracy                           0.98       519
   macro avg       0.95      0.96      0.95       519
weighted avg       0.98      0.98      0.98       519


Accuracy of the model:  0.9845857418111753


In [ ]:
'''For both extra trees and random forest algorithms, we are getting lower than base model of DT. This is so due to 
the majority voting may be randomly classes are selected and miss classfications due to which accuracy dropped. 
Hence we go back to base DT. Where base DT doesn't perform well this ensemble model may give better results'''

### Boosting 

#### Model1: AdaBoost Classfier 

In [92]:
'''We can give the hyper parameters related to decision tree DecisionTreeClassifier(random_state=10,criterion etc)'''

from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
model_AdaBoost=AdaBoostClassifier(base_estimator=DecisionTreeClassifier(random_state=10),n_estimators=10,random_state=10)
model_AdaBoost.fit(X_train,Y_train)
Y_pred=model_AdaBoost.predict(X_test)

In [93]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print()

print("classification report:")
print(classification_report(Y_test,Y_pred))

print()

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[ 99   2   1   0]
 [  4  17   0   0]
 [  0   0 371   0]
 [  1   0   0  24]]

classification report:
              precision    recall  f1-score   support

           0       0.95      0.97      0.96       102
           1       0.89      0.81      0.85        21
           2       1.00      1.00      1.00       371
           3       1.00      0.96      0.98        25

    accuracy                           0.98       519
   macro avg       0.96      0.94      0.95       519
weighted avg       0.98      0.98      0.98       519


Accuracy of the model:  0.9845857418111753


#### Model2: GradientBoosting Classfier 

In [106]:
from sklearn.ensemble import GradientBoostingClassifier
model=GradientBoostingClassifier(n_estimators=150,random_state=10)
model.fit(X_train,Y_train)
Y_pred=model.predict(X_test)

In [107]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print()

print("classification report:")
print(classification_report(Y_test,Y_pred))

print()

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[101   1   0   0]
 [  0  21   0   0]
 [  0   0 371   0]
 [  0   0   0  25]]

classification report:
              precision    recall  f1-score   support

           0       1.00      0.99      1.00       102
           1       0.95      1.00      0.98        21
           2       1.00      1.00      1.00       371
           3       1.00      1.00      1.00        25

    accuracy                           1.00       519
   macro avg       0.99      1.00      0.99       519
weighted avg       1.00      1.00      1.00       519


Accuracy of the model:  0.9980732177263969


In [ ]:
'''By Above Boosting techniques we see that Gradient Boosting is giving better results than base DT. This is generally 
one of the tuning techniques of DT. Ideally these ensembling techniques are complex and expensive, hence in industry
we generally go for base DT than these techniques'''

### Ensemble 

In [128]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import VotingClassifier

# create the sub models
estimators = []
model1 = LogisticRegression()
estimators.append(('log', model1))
model2 = DecisionTreeClassifier(criterion='gini',random_state=10)
estimators.append(('cart', model2))
model3 = SVC(kernel="rbf", C=50,gamma=0.1)
estimators.append(('svm', model3))
model4 = KNeighborsClassifier(n_neighbors=8, metric='euclidean')
estimators.append(('knn', model4))


# create the ensemble model
ensemble = VotingClassifier(estimators)
ensemble.fit(X_train,Y_train)
Y_pred=ensemble.predict(X_test)

C:\Users\Neeharika\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Neeharika\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [129]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print()

print("classification report:")
print(classification_report(Y_test,Y_pred))

print()

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[101   1   0   0]
 [  4  17   0   0]
 [  2   0 369   0]
 [  2   0   0  23]]

classification report:
              precision    recall  f1-score   support

           0       0.93      0.99      0.96       102
           1       0.94      0.81      0.87        21
           2       1.00      0.99      1.00       371
           3       1.00      0.92      0.96        25

    accuracy                           0.98       519
   macro avg       0.97      0.93      0.95       519
weighted avg       0.98      0.98      0.98       519


Accuracy of the model:  0.9826589595375722


In [ ]:
'''As we know this is multi class, we remove logistic and go further'''

In [130]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import VotingClassifier

# create the sub models
estimators = []
model2 = DecisionTreeClassifier(criterion='gini',random_state=10)
estimators.append(('cart', model2))
model3 = SVC(kernel="rbf", C=50,gamma=0.1)
estimators.append(('svm', model3))
model4 = KNeighborsClassifier(n_neighbors=8, metric='euclidean')
estimators.append(('knn', model4))


# create the ensemble model
ensemble = VotingClassifier(estimators)
ensemble.fit(X_train,Y_train)
Y_pred=ensemble.predict(X_test)

In [131]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print()

print("classification report:")
print(classification_report(Y_test,Y_pred))

print()

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[101   1   0   0]
 [  2  19   0   0]
 [  0   0 371   0]
 [  1   0   0  24]]

classification report:
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       102
           1       0.95      0.90      0.93        21
           2       1.00      1.00      1.00       371
           3       1.00      0.96      0.98        25

    accuracy                           0.99       519
   macro avg       0.98      0.96      0.97       519
weighted avg       0.99      0.99      0.99       519


Accuracy of the model:  0.9922928709055877


In [ ]:
'''By individual model accuracies we saw that tuned SVM and base DT are good. Hence we go and build taking only these models'''

In [132]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import VotingClassifier

# create the sub models
estimators = []
model2 = DecisionTreeClassifier(criterion='gini',random_state=10)
estimators.append(('cart', model2))
model3 = SVC(kernel="rbf", C=50,gamma=0.1)
estimators.append(('svm', model3))


# create the ensemble model
ensemble = VotingClassifier(estimators)
ensemble.fit(X_train,Y_train)
Y_pred=ensemble.predict(X_test)

In [133]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print()

print("classification report:")
print(classification_report(Y_test,Y_pred))

print()

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[102   0   0   0]
 [  2  19   0   0]
 [  0   0 371   0]
 [  1   0   0  24]]

classification report:
              precision    recall  f1-score   support

           0       0.97      1.00      0.99       102
           1       1.00      0.90      0.95        21
           2       1.00      1.00      1.00       371
           3       1.00      0.96      0.98        25

    accuracy                           0.99       519
   macro avg       0.99      0.97      0.98       519
weighted avg       0.99      0.99      0.99       519


Accuracy of the model:  0.9942196531791907
