In [2]:
import pandas as pd
import numpy as np

In [3]:
insurance_data=pd.read_csv(r"C:\Python Imarticus\Basics\Assignments\Decision Tree & Ensemble Modelling\Term Insurance Customer Prediction\Insurance_Marketing.csv",header=0)
insurance_data.head()

Age  Job  Marital  Qualification  Default_Premium  Health_Insurance  \
0   56    3        1              0                0                 0   
1   57    7        1              1                1                 0   
2   37    7        1              1                0                 2   
3   40    0        1              0                0                 0   
4   56    7        1              1                0                 0   

   General_Insurance  Contact  Month  Last_Contact_Day  ...  \
0                  0        1      6                 1  ...   
1                  0        1      6                 1  ...   
2                  0        1      6                 1  ...   
3                  0        1      6                 1  ...   
4                  2        1      6                 1  ...   

   Contacts_During_Campaign  Previous_Contact_Days  Contacts_Before_Campaign  \
0                         1                    999                         0   
1                         1                    999                         0   
2                         1                    999                         0   
3                         1                    999                         0   
4                         1                    999                         0   

   Previous_Outcome  Employement_Rates  Price_Variation  \
0                 1                1.1        94.159686   
1                 1                1.1        93.374479   
2                 1                1.1        94.100629   
3                 1                1.1        92.772613   
4                 1                1.1        93.241248   

   Consumer_Confidence_Index  Insurance_Rate  No_Employees  Client_Subscribed  
0                 -38.173679        3.543298   5074.493963                  0  
1                 -33.312428        6.013585   5125.221264                  0  
2                 -51.947349        2.784063   5205.455324                  0  
3                 -35.624584        4.459237   5096.139930                  0  
4                 -33.492147        3.988744   5112.681264                  0  

[5 rows x 21 columns]

In [4]:
print(insurance_data.shape)
print()
print(insurance_data.info())

(41188, 21)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Age                        41188 non-null  int64  
 1   Job                        41188 non-null  int64  
 2   Marital                    41188 non-null  int64  
 3   Qualification              41188 non-null  int64  
 4   Default_Premium            41188 non-null  int64  
 5   Health_Insurance           41188 non-null  int64  
 6   General_Insurance          41188 non-null  int64  
 7   Contact                    41188 non-null  int64  
 8   Month                      41188 non-null  int64  
 9   Last_Contact_Day           41188 non-null  int64  
 10  Last_Contact_Duration      41188 non-null  int64  
 11  Contacts_During_Campaign   41188 non-null  int64  
 12  Previous_Contact_Days      41188 non-null  int64  
 13  Contacts_Before_Campaign   41188 

In [5]:
insurance_data.isnull().sum()

Age                          0
Job                          0
Marital                      0
Qualification                0
Default_Premium              0
Health_Insurance             0
General_Insurance            0
Contact                      0
Month                        0
Last_Contact_Day             0
Last_Contact_Duration        0
Contacts_During_Campaign     0
Previous_Contact_Days        0
Contacts_Before_Campaign     0
Previous_Outcome             0
Employement_Rates            0
Price_Variation              0
Consumer_Confidence_Index    0
Insurance_Rate               0
No_Employees                 0
Client_Subscribed            0
dtype: int64

In [6]:
insurance_df=pd.DataFrame.copy(insurance_data)

In [7]:
'''Last_Contact_Duration: attribute highly affects the output target (e.g., if duration=0 then Client_Subscribed='no'). 
Yet, the duration is not known before a call is performed. Also, after the end of the call y is obviously known. 
Thus, this input should only be included for benchmark purposes and should be discarded if the intention is to have 
a realistic predictive model.'''

insurance_df=insurance_df.drop(['Last_Contact_Duration'],axis=1)

In [8]:
insurance_df.shape

(41188, 20)

In [9]:
X=insurance_df.values[:,:-1]
Y=insurance_df.values[:,-1]
Y=Y.astype(int)

In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3,random_state=10)

In [12]:
#Decision tree

from sklearn.tree import DecisionTreeClassifier
model_DecisionTree=DecisionTreeClassifier(criterion='gini',random_state=10)
model_DecisionTree.fit(X_train,Y_train)
Y_pred=model_DecisionTree.predict(X_test)

In [13]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print()

print("classification report:")
print(classification_report(Y_test,Y_pred))

print()

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[9874 1061]
 [ 986  436]]

classification report:
              precision    recall  f1-score   support

           0       0.91      0.90      0.91     10935
           1       0.29      0.31      0.30      1422

    accuracy                           0.83     12357
   macro avg       0.60      0.60      0.60     12357
weighted avg       0.84      0.83      0.84     12357


Accuracy of the model:  0.8343449057214535


In [14]:
print(list(zip(insurance_df.columns,model_DecisionTree.feature_importances_)))

[('Age', 0.0760644887125595), ('Job', 0.03691327261093972), ('Marital', 0.013511553793415964), ('Qualification', 0.02985284679951267), ('Default_Premium', 0.0067930850150425305), ('Health_Insurance', 0.009320992938503258), ('General_Insurance', 0.013295706566202721), ('Contact', 0.01175640682151075), ('Month', 0.03987911640494868), ('Last_Contact_Day', 0.03884207145150901), ('Contacts_During_Campaign', 0.030665255402692604), ('Previous_Contact_Days', 0.1122115539667022), ('Contacts_Before_Campaign', 0.012717105691868224), ('Previous_Outcome', 0.004680547714184363), ('Employement_Rates', 0.0818604219333383), ('Price_Variation', 0.11939852611995026), ('Consumer_Confidence_Index', 0.11839321237607209), ('Insurance_Rate', 0.11355539834181237), ('No_Employees', 0.13028843733923476)]


In [15]:
#Plot DT

from sklearn import tree
with open("C:\Python Imarticus\Basics\Plots_Reports\insurance_model_DecisionTree.txt", "w") as f:
    f = tree.export_graphviz(model_DecisionTree, feature_names=insurance_df.columns[:-1],out_file=f)

In [16]:
model_DecisionTree.get_depth()

38

In [17]:
# Pruning DT

from sklearn.tree import DecisionTreeClassifier
model_DecisionTree=DecisionTreeClassifier(criterion='gini',min_samples_leaf=5,max_depth=25,random_state=10)
model_DecisionTree.fit(X_train,Y_train)
Y_pred=model_DecisionTree.predict(X_test)

In [18]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print()

print("classification report:")
print(classification_report(Y_test,Y_pred))

print()

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[10243   692]
 [ 1015   407]]

classification report:
              precision    recall  f1-score   support

           0       0.91      0.94      0.92     10935
           1       0.37      0.29      0.32      1422

    accuracy                           0.86     12357
   macro avg       0.64      0.61      0.62     12357
weighted avg       0.85      0.86      0.85     12357


Accuracy of the model:  0.86185967467832


In [19]:
#Plot DT

from sklearn import tree
with open("C:\Python Imarticus\Basics\Plots_Reports\insurance_pruned_model_DecisionTree.txt", "w") as f:
    f = tree.export_graphviz(model_DecisionTree, feature_names=insurance_df.columns[:-1],out_file=f)

In [20]:
#Random Forest

from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=200,random_state=10)
model.fit(X_train,Y_train)
Y_pred=model.predict(X_test)

In [21]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print()

print("classification report:")
print(classification_report(Y_test,Y_pred))

print()

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[10753   182]
 [ 1113   309]]

classification report:
              precision    recall  f1-score   support

           0       0.91      0.98      0.94     10935
           1       0.63      0.22      0.32      1422

    accuracy                           0.90     12357
   macro avg       0.77      0.60      0.63     12357
weighted avg       0.87      0.90      0.87     12357


Accuracy of the model:  0.8952011005907583


In [22]:
#AdaBoost

from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
model_AdaBoost=AdaBoostClassifier(base_estimator=DecisionTreeClassifier(random_state=10),n_estimators=50,random_state=10)
model_AdaBoost.fit(X_train,Y_train)
Y_pred=model_AdaBoost.predict(X_test)

In [23]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print()

print("classification report:")
print(classification_report(Y_test,Y_pred))

print()

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[9862 1073]
 [ 990  432]]

classification report:
              precision    recall  f1-score   support

           0       0.91      0.90      0.91     10935
           1       0.29      0.30      0.30      1422

    accuracy                           0.83     12357
   macro avg       0.60      0.60      0.60     12357
weighted avg       0.84      0.83      0.84     12357


Accuracy of the model:  0.8330500930646597


In [24]:
#gradient boost

from sklearn.ensemble import GradientBoostingClassifier
model=GradientBoostingClassifier(n_estimators=150,random_state=10)
model.fit(X_train,Y_train)
Y_pred=model.predict(X_test)

In [25]:

from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print()

print("classification report:")
print(classification_report(Y_test,Y_pred))

print()

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[10786   149]
 [ 1135   287]]

classification report:
              precision    recall  f1-score   support

           0       0.90      0.99      0.94     10935
           1       0.66      0.20      0.31      1422

    accuracy                           0.90     12357
   macro avg       0.78      0.59      0.63     12357
weighted avg       0.88      0.90      0.87     12357


Accuracy of the model:  0.896091284292304


In [26]:
#SVM 

from sklearn import svm
classifier=svm.SVC(kernel="rbf", gamma=0.1, C=50)
classifier.fit(X_train,Y_train)
Y_pred=classifier.predict(X_test)

In [27]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print()

print("classification report:")
print(classification_report(Y_test,Y_pred))

print()

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[10222   713]
 [ 1046   376]]

classification report:
              precision    recall  f1-score   support

           0       0.91      0.93      0.92     10935
           1       0.35      0.26      0.30      1422

    accuracy                           0.86     12357
   macro avg       0.63      0.60      0.61     12357
weighted avg       0.84      0.86      0.85     12357


Accuracy of the model:  0.8576515335437404


In [28]:
#Logistic 

from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(X_train,Y_train)
Y_pred=classifier.predict(X_test)

C:\Users\Neeharika\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [29]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print()

print("classification report:")
print(classification_report(Y_test,Y_pred))

print()

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[10809   126]
 [ 1176   246]]

classification report:
              precision    recall  f1-score   support

           0       0.90      0.99      0.94     10935
           1       0.66      0.17      0.27      1422

    accuracy                           0.89     12357
   macro avg       0.78      0.58      0.61     12357
weighted avg       0.87      0.89      0.87     12357


Accuracy of the model:  0.894634620053411


In [32]:
#Ensembled Model 

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import VotingClassifier

# create the sub models
estimators = []
model1 = LogisticRegression()
estimators.append(('log', model1))
model2 = DecisionTreeClassifier(criterion='gini',min_samples_leaf=5,max_depth=25,random_state=10)
estimators.append(('cart', model2))
model4=RandomForestClassifier(n_estimators=200,random_state=10)
estimators.append(('RandomForest', model4))
model5=GradientBoostingClassifier(n_estimators=150,random_state=10)
estimators.append(('GradientBoost', model5))

# create the ensemble model
ensemble = VotingClassifier(estimators)
ensemble.fit(X_train,Y_train)
Y_pred=ensemble.predict(X_test)

C:\Users\Neeharika\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [33]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print()

print("classification report:")
print(classification_report(Y_test,Y_pred))

print()

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[10816   119]
 [ 1162   260]]

classification report:
              precision    recall  f1-score   support

           0       0.90      0.99      0.94     10935
           1       0.69      0.18      0.29      1422

    accuracy                           0.90     12357
   macro avg       0.79      0.59      0.62     12357
weighted avg       0.88      0.90      0.87     12357


Accuracy of the model:  0.8963340616654528


In [ ]:
'''Over all we see that Gradient Boost classifier is better in terms of f1 score and type2 error though accuracy is more for ensemled model'''